Hinducode threads
ruslanTankist/sem1_c_task2 pull request #1
Opened 2020-03-23 13:18 UTC by ruslanTankist

ИЗ№2, Юзеев Руслан, АПО-12

Условие ИЗ №2: Сравните и выведите в консоль время работы последовательного и параллельного с использованием нескольких потоков алгоритмов, каждый из которых выделяет в динамической памяти числовой массив размером 100 Мб и инициализирует его значениями по следующему шаблону: 0, 1, 2, 3, 0, 1, 2, 3, …

2020-03-24 21:44 UTC, babayanv requested changes

2020-03-24 21:44 UTC, babayanv commented on CMakeLists.txt
> +# -fprofile-arcs - Insert arc-based program profiling code
Убери ненужные комментарии

2020-03-24 21:44 UTC, babayanv commented on functionality.h
> +#define REQUIRED_SIZE 100000000 //100 Mb
Константы лучше объявлять по месту использования

2020-03-24 21:44 UTC, babayanv commented on main.c
> +    if(success == 1) { printf("Error in non_parallel()\n"); return 0; }
Даже если так делать можно, не значит, что так делать - ок.
1 операция - 1 строка

2020-03-24 21:44 UTC, babayanv commented on functionality.c
> +    int array_size = REQUIRED_SIZE / sizeof(int);
Размер типа char по стандарту - 1 байт. Можно не мучаться с индексацией и воспользоваться этим.

У тебя array_size * sizeof(int) по-факту будет меньше, чем REQUIRED_SIZE. То есть заполняешь ты не все 100 мб

2020-03-24 21:44 UTC, babayanv commented on functionality.c
> +    if( array == 0 ) { printf("malloc() failed\n"); return 1; }
От всяких принтов лучше отказаться. Они замедляют выполнение твоей программы и просто здесь не нужны

2020-03-24 21:44 UTC, babayanv commented on functionality.c
> +    for(int i = 0; i < array_size; i++)
Для индексов массивов рекомендуется использовать тип size_t

2020-03-24 21:44 UTC, babayanv commented on functionality.c
> +    int bit_one = 0, bit_two = 0;
1 строка - переменная

2020-03-24 21:44 UTC, babayanv commented on functionality.c
> +    int pid = fork();
К сожалению, это работает не так, как ты думаешь. fork() создает дочерний процесс. Сразу после форка память у обоих процеесов одна и та же. Однако, если ты попытаешься что-то записать по имеющимся адресам, произойдет копирование в новый участок памяти. Это так называемый `copy on write`. То есть, в действительности в твоей программе массив не будет заполнен 0, 1, 2, 3 и тд. На самом деле будет создано 4 копии этого массива, в каждом из которых будет заполнена лишь 1/4 его часть.

Здесь необходимо было использовать потоки, как и сказано в задании. Потоки делят память между собой и такое заполнение будет возможно.

2020-03-24 21:49 UTC, babayanv commented on test.cpp
> +    EXPECT_TRUE( parallel() == 0);
Я сомневаюсь, что эти тесты что-то проверяют)

2020-03-24 21:49 UTC, babayanv commented on test.cpp
> +    EXPECT_TRUE( parallel() == 0);
Здесь как раз бы не помешал тест, который проверяет, что массив был заполнен верно. Как раз он бы и позволил эту ошибку выявить намного раньше)

2020-03-25 09:48 UTC, ruslanTankist commented on functionality.h
> +#define REQUIRED_SIZE 100000000 //100 Mb
gtest просит эту же константу, поэтому оставил её в .h

2020-03-25 19:28 UTC, babayanv commented on functionality.c
> +        int * arg = (int *)malloc(sizeof(int));
зачем это выделять на куче?

2020-03-25 19:29 UTC, babayanv commented on functionality.c
> +        int * arg = (int *)malloc(sizeof(int));
+ утечка памяти, нигде жтот инт не освобождается

2020-03-25 19:31 UTC, babayanv commented on functionality.c
> +    }
```c
while (data.job_done[0] &&
       data.job_done[1] &&
       ...
);
```

2020-03-25 19:33 UTC, babayanv commented on functionality.c
> +        free(arr);
free отработает корректно и для NULL

2020-03-25 19:38 UTC, babayanv commented on functionality.c
> +            if(errflag != 0) continue;
У тебя каждый тред работает со своим куском. Смысла в мьютексте здесь не вижу

2020-03-25 19:38 UTC, babayanv commented on functionality.c
> +            if(errflag != 0) continue;
Тем более, что задача в том, чтобы сравнить время выполнения двух подходов, здесь - явно оверхед на кучу всего

2020-03-25 19:40 UTC, babayanv commented on functionality.c
> +    char * array = malloc(REQUIRED_SIZE);
Там, где выделяешь память, ее и надо освобождать, если это возможно. Логичнее будет выделять память на уровне выше, а сюда передавать готовый указатель

2020-03-25 19:40 UTC, babayanv commented on functionality.c
> +    if( array == 0 ) { return NULL; }
Для вербозности - `array == NULL`

2020-03-25 19:41 UTC, babayanv commented on functionality.c
> +    if( array == 0 ) { return NULL; }
1 операция на 1 строке - не пофикшено

2020-03-25 19:41 UTC, babayanv commented on functionality.c
> +}
Разделяй код на логические блоки. Так его будет легче читать

2020-03-25 19:42 UTC, babayanv commented on functionality.c
> +    char * array; //array of int here
в массиве не int, а char

2020-03-25 19:42 UTC, babayanv commented on functionality.c
> +    char * array; //array of int here
Здесь и без комментария понятно, что поле - это массив чаров)

2020-03-25 19:43 UTC, babayanv commented on functionality.c
> +            if(errflag != 0) continue;
Тем более, если каждый тред использует один и тот же мьютекс, то тут они все равно будут работать по очереди. НИкакого параллелизма не будет

2020-03-25 19:44 UTC, babayanv commented on functionality.c
> +        while (1)
Зачем здесь еще один цикл?

2020-03-25 19:53 UTC, babayanv commented on functionality.c
> +    }
Вместо того, чтобы крутить циклы, лучше бы просто вызвал 4 раза эту функцию)

2020-03-25 19:54 UTC, babayanv commented on functionality.c
> +    }
А вообще в этом нет никакого смысла. Для того, чтобы заблокироваться до завершения потока есть pthread_join

2020-03-25 19:58 UTC, babayanv commented on functionality.c
> +    free(arg);
Так вот где он освобождается. 

Не делай так. Где выделил, там и освобождай

2020-03-26 20:37 UTC, babayanv commented on functionality.c
> +}
Чем тогда, собсно, сам free не устраивает?

2020-03-29 17:24 UTC, merged